### ISSUE TITLE
[BUG] Cannot run protonvpn-cli as user, only as root in a root shell.

### ISSUE THREAD

**Issue by gserl** [ProtonVPN/protonvpn-cli-ng#64]
Each and every time I try to run the binary via `$ sudo protonvpn init`, I receive the error: 
`[!] The program was not executed as root.
 [!] Plase run as root`. 

The log throws an SELinux error at the same time as well --> "SELinux is preventing /usr/libexec/platform-python3.6 from using the dac_override capability."

The only way I am able to create a config and connect is via direct root login shell, and keeping that root shell open for as long as I'm using the VPN. 

Tried the 'virtualenv' mode of install as suggested, to no avail. Tried adding the 'NOPASSWD' directive in the sudoers file, also as suggested, this doesn't work either. Perhaps its an SELinux issue? No problems at all if I simply open a root shell and run it exclusively in there.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
Nothing shown of relevance in pvpn-cli.log
`$ which protonvpn` shows `/usr/local/bin/protonvpn`. This path is in my shell $PATH.

**Desktop**
 - OS: RHEL 8.1
 - Python Version:  3.6.8 
 - ProtonVPN-CLI Version: 2.1.2

**Comment by Rafficer** [comment]
Try with `setenforce 0` temporarily. If it works, you know it's a SELinux thing.

**Comment by gserl** [comment]
Tried that, didn't work. Issuing `$ sudo protonvpn c -f` gives: `sudo: protonvpn: command not found`. Issuing `$ which protonvpn` gives `/usr/local/bin/protonvpn`. I've verified that `/usr/local/bin` is in my shell PATH.

Side note: I am also unable to use Syncthing on 2 boxes each of which are running protonvpn-cli-ng, unless I disconnect the VPN on the rhel8 end.

**Comment by Rafficer** [comment]
Add `/usr/local/bin` to roots path. That's what sudo searches.

**Comment by gserl** [comment]
Its already in the root PATH, I checked.

**Comment by Rafficer** [comment]
So you added it manually? Cause it's not by default on RHEL.

**Comment by gserl** [comment]
I don't think I ever added it manually, but it is in the PATH:
`[root@rhel8.1 ~]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin`

**Comment by Rafficer** [comment]
How did you change to root? This could be carried over from how you changed user.

**Comment by gserl** [comment]
used su -

**Comment by Rafficer** [comment]
Use `sudo -s`, then check $PATH. That shows you the directories that sudo sees. `/usr/local/bin` isn't in there by default.

**Comment by gserl** [comment]
You're right, when I use `sudo -s`, the $PATH is: `/sbin:/bin:/usr/sbin:/usr/bin`. I was under the impression that `su -` or `su --login` initializes the  environment  variables  HOME,  SHELL, USER, LOGNAME, and PATH, I should probably stay away from using `su` at all on RHEL or any distro that uses a `wheel` group, and just use `sudo -s` as you suggested.

**Comment by Rafficer** [comment]
> I will add /usr/local/bin to the root path(is this safe?).

It shouldn't cause any issues. All other distors (including Fedora) do this anyway (Output on Fedora 31: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`).

Another option would be to symlink the `protonvpn` executable to one of the other directories, but that's not as clean IMO.

**Comment by gserl** [comment]
OK, I appended `usr/local/bin` to PATH by adding it to `/root/.bash_profile`(login/non-interactive shells) and `/root/.bashrc`(interactive shells). I verified that `usr/local/bin` is present in the root path via both `sudo -s` and `sudo -i` logins. 

Still when I type `$ sudo protonvpn init` from my user account shell, I get `sudo: protonvpn: command not found`.  Logged in and out of the machine first. When I login to root using `sudo -i`(login shell) or `sudo -s`(interactive shell), and issue a protonvpn command, it tells me `There is no profile initialized yet. Please run 'protonvpn init`. There is already a working profile under `/root/.pvpn-cli`. When I login to root using `$ su -`, the profile is there and I can use protonvpn no problem. I am baffled.

Another problem I noticed is that when I change the Default Protocol from UDP to TCP and save it, there are resultant syntax errors in `/root/.pvpn-cli/pvpn-cli.cfg`. The entry for `default_protocol = udp` is never erased, its still there, while the new entry for tcp is misspelled as `default_protocl = tcp`.

Maybe I should just give up running this on RHEL, never had any trouble on Ubuntu, all I want to do is run protonvpn in a user account like usual.

Side note( I mentioned this  a few posts up): Syncthing(folder-sync tool) will not work between this RHEL8.1 box and an Ubuntu box unless I disconnect the VPN from both ends; tried using TCP instead of UDP, didn't help.

**Comment by Rafficer** [comment]
> Another problem I noticed is that when I change the Default Protocol from UDP to TCP and save it, there are resultant syntax errors in /root/.pvpn-cli/pvpn-cli.cfg. The entry for default_protocol = udp is never erased, its still there, while the new entry for tcp is misspelled as default_protocl = tcp.

Thanks for that. I'll add a fix right away.

For the rest: I'm setting up a CentOS 8 box to test and report back how I fixed the command not found issues.

For the syncthing problem: Did you activate the Kill Switch? Try without it. If not, check if it works when you manually use OpenVPN to connect (you can find instructions on https://protonvpn.com/support. I don't think that's an issue caused by the CLI.

**Comment by Rafficer** [comment]
Alright, gave you some wrong advice. It's not root's $PATH, it's in the sudoers file that essentially sets where to search. To fix it, edit the sudoers file with `sudo visudo`, locate the line that says `Defaults secure_path = ...` and append the `/usr/local/bin` path to the other folders listed there. Then it works.

**Comment by gserl** [comment]
Your suggestion to disable Kill Switch worked for Syncthing, thanks very much for that.

OK here's something I probably should have realized to begin with.  There is no `usr/local/bin` at all on RHEL8.1; there is a `usr/bin` but no `/usr/local/bin`. When installing protonvpn-cli, the directory is created by pip3. 

`/usr/local/bin` created during the install process, has 755-permissions and SELinux `unconfined_u:object_r:usr_t:s0` context, whereas `/usr/bin` has 555-permissions and `system_u:object_r:bin_t:s0` context. Not sure what this means or if it helps you, but I noticed that.

I appended `/usr/local/bin` to that section of the `/etc/sudoers` file via `sudo visudo`. It looks like this: `Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin`. 

Logged out, even restarted, but its still not working, issuing `sudo protonvpn init` shows the same error message:
`[!] The program was not executed as root.`
`[!] Please run as root.`

Again I tried the virtualenv install method, also to no avail. 
I'm trying to see if I'm missing something obvious but not coming up with any ideas at the moment

**Comment by Rafficer** [comment]
Good to see that it's working. It's probably best to create an alias in your `~/.bashrc` file to make this easier:

`alias protonvpn='sudo -i protonvpn'`

I wasn't able to reproduce this, though. After I added the path to the `sudoers` file, it worked. Even with just using `sudo protonvpn`.

**Comment by gserl** [comment]
I noticed RHEL and CentOS are not necessarily 100% identical, for example there was no `ifconfig` command in CentOS8_1905 but it is still present in RHEL8.1...Noticed a few other minor discrepancies between the distros too beyond the cosmetic and commercial ones, I'll chalk it up to that for now but still baffled why I have to use `$ sudo -i` and not just plain `$ sudo` ... If I figure anything out I'll post it here, and thanks again for your efforts in helping me with all this, much appreciated :)

**Comment by gserl** [comment]
Strange I just did another fresh RHEL8.1 install on a different physical machine, nearly untouched, had precisely the same issue, had to use `sudo -i` all the time.

**Comment by jwflory** [comment]
@gserl You mentioned using RHEL 8. In the future, I'm working to package this officially for EPEL 8. For the meantime, I made a RPM package on Fedora COPR [including EPEL 8 builds](https://copr.fedorainfracloud.org/coprs/jflory7/protonvpn-cli/). I run an enforcing SELinux policy that is required on the systems I operate on (i.e. disabling is not an option). The RPM package in the COPR works for me on Fedora 31 but it's the same package for EPEL 8.

Curious if my RPM package solves your SELinux issues.

**Comment by gserl** [comment]
@jwflory Thanks for suggesting that. I tried your COPR build, during install on RHEL8.1, I got a `Error: 
 Problem: cannot install the best candidate for the job - nothing provides python3-dialog`. There is no `python3-dialog` package in my repos unless its under a different name which I could not readily find. I then tried to install `python3-dialog-3.3.0-20.fc32.noarch.rpm` from Fedora Rawhide but manual install of that failed too.

Anyway, I finished the install of your protonvpn-cli rpm package using the `--nobest` option. Install completed, issuing `which protonvpn` showed `/usr/bin/protonvpn`(whereas it used to be `/usr/local/bin`), but still cannot access the binary without using `sudo -i'. Using `sudo` or `sudo -s` fails with: [!] The program was not executed as root.
[!] Please run as root.

**Comment by jatin-cbs** [comment]
I also use RHEL 8.1 When I do sudo -s, usr/local/bin does not show in my $PATH can someone tell me how to ?

**Comment by jatin-cbs** [comment]
In my vase sudo -i also does not work

**Comment by jatin-cbs** [comment]
> Your suggestion to disable Kill Switch worked for Syncthing, thanks very much for that.
> 
> OK here's something I probably should have realized to begin with. There is no `usr/local/bin` at all on RHEL8.1; there is a `usr/bin` but no `/usr/local/bin`. When installing protonvpn-cli, the directory is created by pip3.
> 
> The `/usr/local/bin` directory created during the install process, has 755-permissions and SELinux `unconfined_u:object_r:usr_t:s0` context, whereas `/usr/bin` has 555-permissions and `system_u:object_r:bin_t:s0` context. Not sure what this means or if it helps you, but I noticed that. I'm assuming that's intentional and by design.
> 
> I appended the directory to the `secure_path =` section of `/etc/sudoers`. Issuing `sudo -i protonvpn init` then worked, and created the config files in my home directory, and using `sudo -i protonvpn c -f` connected successfully. Using `sudo` by itself without the `-i` option does not work, nor does the `-s` option, even with appending the path to `/etc/sudoers`.
> 
> `[gs@rhel8 ~]$ sudo -s protonvpn c -f`
> `[!] The program was not executed as root.`
> `[!] Please run as root.`
> [`gs@rhel8 ~]$ sudo protonvpn c -f`
> `[!] The program was not executed as root.`
> `[!] Please run as root.`
> `[gs@rhel8 ~]$ sudo -i protonvpn c -f`
> `Connecting to US-NY#101 via UDP...`
> `Connected!`
> `[gs@rhel8 ~]$`

Can you explain how this worked ?

**Comment by jatin-cbs** [comment]
Where is the secure_path line ? its so big cant find it

**Comment by jatin-cbs** [comment]
Ok I did it and command started working with sudo -i parameter but its says coonection timed out after 45 seconds on any server.

**Comment by jatin-cbs** [comment]
![Screenshot from 2019-12-29 22-07-15](https://user-images.githubusercontent.com/40650341/71559738-e9d19700-2a87-11ea-8dd3-2254b6809208.png)

**Comment by Rafficer** [comment]
What's the content of `~/.pvpn-cli/ovpn.log`?

**Comment by jatin-cbs** [comment]
Sun Dec 29 22:14:41 2019 OpenVPN 2.4.8 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Nov  1 2019
Sun Dec 29 22:14:41 2019 library versions: OpenSSL 1.1.1c FIPS  28 May 2019, LZO 2.08
Sun Dec 29 22:14:41 2019 ERROR: username from Auth authfile '/home/SHuRiKeN/.pvpn-cli/pvpnpass' is empty
Sun Dec 29 22:14:41 2019 Exiting due to fatal error

**Comment by jatin-cbs** [comment]
My credentials i copy pasted from my dashboard and still its not working.

**Comment by Rafficer** [comment]
They're empty. Are you sure you pasted something?

**Comment by jatin-cbs** [comment]
I re did it it worked my bad, maybe it didnt got pasted before deleting previous comments to focus on main issue.

**Comment by gserl** [comment]
Quick update to this thread: I was able to use `sudo protonvpn init` on a CentOS 8 VM instance same as mentioned above by Rafficer, but still forced to use `sudo -i` with protonvpn-cli commands in Red Hat 8.1 ... In both cases I must append `/usr/local/bin` to the `Defaults secure_path=` line of `/etc/sudoers`.

**Comment by Serokin** [comment]
I got around this by updating utils.py to check against euid in Centos 8.

getpass.getuser() won't return as "root" unless you use ```sudo -i```
https://bugs.python.org/issue34709
```
def check_root():
    """Check if the program was executed as root and prompt the user."""
    if getpass.getuser() != "root" and os.geteuid() != 0:
        print(

            "[!] The program was not executed as root.\n"
            "[!] Please run as root."
        )
        logger.debug("Program wasn't executed as root")
        sys.exit(1)
    else:
        # Check for dependencies
        dependencies = ["openvpn", "ip", "sysctl", "pgrep", "pkill"]
        for program in dependencies:
            check = subprocess.run(["which", program],
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE)
            if not check.returncode == 0:
                logger.debug("{0} not found".format(program))
                print("'{0}' not found. \n".format(program),
                      "Please install {0}.".format(program))
                sys.exit(1)

```

**Comment by Rafficer** [comment]
Awesome, thanks! Would you like to submit a PR? :)
